### ISSUE TITLE
PA Review: Reviews

### ISSUE THREAD

**Issue by LuuuFan** [LuuuFan/Celp#20]
- [x]  Backend: DB, model, controller, views
- [x]  Redux Loop: ajax, actions, reducer
- [x]  Presentational Components
- [x]  Styling
- [x]  Smooth, bug-free navigation
- [x]  Adequate and appropriate seeds

**Comment by xnanodax** [comment]
Styling
- [x] What is the order in listing reviews? Reverse order?

**Comment by LuuuFan** [comment]
Modified order to updated_at desc

**Comment by xnanodax** [comment]
Nice work! I can Create, Read, and Update the reviews. Delete works but on deletion, a bug arises!
I also see errors rendered when the body is blank.
- [x] Delete a review without a bug

**Question:** I can create a review without selecting a rating, which is fine. Keep in mind that on Yelp, the minimum rating is 1 star instead of 0 stars. What do you want to do?

**Comment by LuuuFan** [comment]
Added validation for rate, have to select a rate at least 1, thanks.

**Comment by xnanodax** [comment]
- [x] When creating a review with a 3 star rating but no body, an error appears "Body can't be blank". Awesome. However, the rating stars doesn't clear and still displays the 3 star rating. Now when I add the body, it says that the "Rate must be greater or equal to 1". Error shown below:
![screen shot 2018-02-06 at 2 19 30 pm](https://user-images.githubusercontent.com/20424731/35887329-ca525bd6-0b48-11e8-9ddd-2bade7dfb0c4.png)

- [x] Change the error message for empty ratings to be more similar to Yelp's
**From Yelp Webpage**
![screen shot 2018-02-06 at 2 22 53 pm](https://user-images.githubusercontent.com/20424731/35887504-505514f8-0b49-11e8-9a57-65350c0f4fd6.png)


- [x] When updating the review, the button on the update form still stays "Post Review" instead of "Update Review"

Suggestions:
- [x] When deleting a post, confirm with the user before deletion. (Yelp does this)

**Comment by LuuuFan** [comment]
Fixed issue :"When creating a review with a 3 star rating but no body, an error appears "Body can't be blank". Awesome. However, the rating stars doesn't clear and still displays the 3 star rating. Now when I add the body, it says that the "Rate must be greater or equal to 1" with add condition check to trigger re-render write-review-component

**Comment by xnanodax** [comment]
Awesome work, Lu! This issue is closed!
