### ISSUE TITLE
PA Review - Search

### ISSUE THREAD

**Issue by LuuuFan** [LuuuFan/Celp#28]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by xnanodax** [comment]
- [x] When searching for the word "cat" from the splash page, I receive the following search results when I tested 3 times. 
**Search from the splash**
![screen shot 2018-02-08 at 2 50 22 pm](https://user-images.githubusercontent.com/20424731/36002570-7e8f9f5e-0cdf-11e8-95cc-549b93de646c.png)

**Searching from not the splash page**
![screen shot 2018-02-08 at 2 52 30 pm](https://user-images.githubusercontent.com/20424731/36002631-b31d0a68-0cdf-11e8-9f32-ffabb3528f96.png)

**Comment by LuuuFan** [comment]
That's a really great bug, Thanks Cynthia! :+1: :+1: :+1: :100: :100:

**Comment by xnanodax** [comment]
This issue is definitely closed. However, just wanted to suggest the following:

- [ ] When searching in different cities, the search results page is different.
**Celp when searching in cities with no data**
![screen shot 2018-02-09 at 2 24 06 pm](https://user-images.githubusercontent.com/20424731/36053116-2986c5de-0da5-11e8-8950-a3a4fc4c5ce6.png)

**Yelp when searching in cities with no data**
![screen shot 2018-02-09 at 2 26 33 pm](https://user-images.githubusercontent.com/20424731/36053136-45385e82-0da5-11e8-9f2e-f4fd5efee605.png)
