### ISSUE TITLE
PA Review: Biz

### ISSUE THREAD

**Issue by LuuuFan** [LuuuFan/Celp#9]
- [x]  Backend: DB, model, controller, views
- [x]  Redux Loop: ajax, actions, reducer
- [x]  Presentational Components
- [x]  Styling
- [x]  Smooth, bug-free navigation
- [x]  Adequate and appropriate seeds

**Comment by xnanodax** [comment]
CRUD
+ Who has permission to edit a business?

Styling
- [x] Align the number of reviews with the number of stars
- [x] Add more padding between the info within the business list item
- [x] Add more padding between different business list items

Show Page
- [x] Search button not aligned with the rest of the box
![screen shot 2018-02-05 at 9 32 39 am](https://user-images.githubusercontent.com/20424731/35819422-8949c418-0a57-11e8-92b6-1cdf9e6b7a22.png)
- [x] The search place holder "Search within the reviews" does not completely display
- [x] Should list hours and more business info.
- [x] Some SVG pixels for the rating is off. Example: There is some red pixels below the 3.5 stars rating. 
![screen shot 2018-02-05 at 9 31 31 am](https://user-images.githubusercontent.com/20424731/35819377-6426bff6-0a57-11e8-8f75-c5535b5785cc.png)

**Comment by LuuuFan** [comment]
CRUD

- Who has permission to edit a business?

-  A: remove edit button for now. If have time, will add create/edit Biz as bonus

**Comment by LuuuFan** [comment]
- Add more padding between different business list items
 Adding sample review to increase the padding between different biz list items

**Comment by LuuuFan** [comment]
List hours doesn't have function yet, will do later in bonus

**Comment by xnanodax** [comment]
- [x] Add more padding between the ordered list numbers and the name of the restaurant.
- [x] Add more padding between the dollar sign/food categories and the star rating.
- [x] In order to achieve the 3 dots for reviews that are longer than the preview, add the following property and values to that css selector.
  ```
    overflow: hidden;
    text-overflow: ellipsis;
  ```
**Yelp Example:**
![screen shot 2018-02-06 at 10 30 53 am](https://user-images.githubusercontent.com/20424731/35877019-f8137e9e-0b28-11e8-9cc7-a3deea459169.png)

**Celp Example:**
![screen shot 2018-02-06 at 10 31 00 am](https://user-images.githubusercontent.com/20424731/35877022-f98c6ad8-0b28-11e8-9f00-41a81f3e96b0.png)

**Comment by LuuuFan** [comment]
Text overflow issue, if using ellipsis, 'read more' link will be kick out from the container.

**Comment by LuuuFan** [comment]
Ajust SVG a little bit, but cannot tell from my end.

**Comment by xnanodax** [comment]
Awesome work! The star SVGs definitely look a lot better when I zoom in and out of the page. This issue is closed :)
